name: ele520
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7
    - pylint
    - pip
    - numpy
    - matplotlib
    - autopep8
    - jupyterlab
    - nbconvert
    - seaborn
    - scikit-learn
    - tensorflow
    - nomkl

